# Dependencies
markdown:         maruku
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            atubo's blog
tagline:          'code and stuff'
description:      'Work hard, play hard'
url:              http://atubo.github.io
baseurl:          /

author:
  name:           'atubo'

paginate:         5

#Custom vars
version:          1

github:
  repo:           https://github.com/atubo
